"""
DAG_METADATA
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
        def print_gcs_info():
            # Extract bucket name and file name from dag_run.conf
            bucket_name = "{{ dag_run.conf['bucket'] }}"
            file_name = "{{ dag_run.conf['name'] }}"
            
            # Print the configuration for debugging
            print(f"Bucket Name: {bucket_name}")
            print(f"File Name: {file_name}")
            
            # Return values which will be automatically pushed to XCom
            return bucket_name, file_name

default_args={
    "owner": "M. Azhar Ali,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-01-30", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "M. Azhar Ali": "mailto:muhalthaf.2580@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm6isj113047101ivie2g134u/cloud-ide/cm6ix8u1h04uo01l0zms13beg/cm6iz7mj605is01mdvh1hykyk",
    },
)
def DAG_METADATA():
    python_1 = python_1_func()

dag_obj = DAG_METADATA()
